In [1]:
import torch

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[0.0000e+00, -0.0000e+00, 0.0000e+00],
        [-0.0000e+00, 1.9618e-44, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.6942, 0.7335, 0.2096],
        [0.5454, 0.6821, 0.5418],
        [0.8342, 0.4399, 0.9782],
        [0.4181, 0.5682, 0.8128],
        [0.7705, 0.3027, 0.2801]])


In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
x[0, 0] = 5.56
x[3, 0] = 2


x

tensor([[5, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [2, 0, 0],
        [0, 0, 0]])

In [6]:
x = torch.tensor([5.5, 3])

In [7]:
x

tensor([5.5000, 3.0000])

In [8]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.1266,  0.7144, -0.4346],
        [-1.0517, -0.5532, -0.8764],
        [-1.1265,  0.7495, -2.2891],
        [-0.0144, -0.0499, -0.3201],
        [-0.6105,  0.9667,  1.9674]])


In [9]:
print(x.size())

torch.Size([5, 3])


In [10]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 0.6539,  1.6181,  0.2281],
        [-0.8843, -0.4962, -0.0487],
        [-0.4623,  1.2244, -2.0111],
        [ 0.5622,  0.2959,  0.4763],
        [-0.0958,  1.0252,  2.7090]])


Methods post fixed with "_" are in-place

In [11]:
y.add_(x)
print(y)

tensor([[ 0.6539,  1.6181,  0.2281],
        [-0.8843, -0.4962, -0.0487],
        [-0.4623,  1.2244, -2.0111],
        [ 0.5622,  0.2959,  0.4763],
        [-0.0958,  1.0252,  2.7090]])


In [12]:
y.copy_(x)
print(y)

tensor([[ 0.1266,  0.7144, -0.4346],
        [-1.0517, -0.5532, -0.8764],
        [-1.1265,  0.7495, -2.2891],
        [-0.0144, -0.0499, -0.3201],
        [-0.6105,  0.9667,  1.9674]])


In [13]:
y.t_()
print(y)

tensor([[ 0.1266, -1.0517, -1.1265, -0.0144, -0.6105],
        [ 0.7144, -0.5532,  0.7495, -0.0499,  0.9667],
        [-0.4346, -0.8764, -2.2891, -0.3201,  1.9674]])


You can use standard NumPy-like indexing:

In [14]:
print(x[:, 1])

tensor([ 0.7144, -0.5532,  0.7495, -0.0499,  0.9667])


Resizing: If you want to resize/reshape tensor, you can use torch.view:

In [15]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())
print(y)
print(z)

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])
tensor([-0.3331,  1.4768,  1.0495,  0.1005,  0.3685,  0.1915,  0.2086, -0.9671,
         0.2118, -1.5667, -0.9982, -0.2269,  0.4987,  0.1419,  2.5014, -0.0235])
tensor([[-0.3331,  1.4768,  1.0495,  0.1005,  0.3685,  0.1915,  0.2086, -0.9671],
        [ 0.2118, -1.5667, -0.9982, -0.2269,  0.4987,  0.1419,  2.5014, -0.0235]])


If you have a one element tensor, use .item() to get the value as a Python number:

In [16]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.7441])
0.744056761264801


**Read later:**

100+ Tensor operations, including transposing, indexing, slicing, mathematical operations, linear algebra, random numbers, etc., are described [here](https://pytorch.org/docs/stable/torch.html).

# Numpy / Pytorch Bridges

In [17]:
a = torch.ones(5)
print(a)

b = a.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


Changing the value of a also changes the value of b:

In [18]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


And the other way around is also true:

In [19]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
a += 1

print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


# CUDA

Check if cuda (GPU) is available:

In [20]:
torch.cuda.is_available()

False

In [21]:
x = torch.randn(5, 3)

To use a specific CUDA device, you can specify it when creating the tensor or move it using the .to(device) method:

(Only works when CUDA is available)

In [22]:
device = torch.device("cuda")          # a CUDA device object
y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
x = x.to(device)                       # or just use strings ``.to("cuda")``
z = x + y
print(z)
print(z.to("cpu", torch.double)) 

AssertionError: Torch not compiled with CUDA enabled